services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        command: pnpm run start:dev
        restart: always
        depends_on:
            - postgres
        env_file:
            - .env
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app

    postgres:
        image: postgres
        env_file:
            - .env
        ports:
            - '5432:5432'
